### ISSUE TITLE
readFixedLength() sometimes contains the corruption of text

### ISSUE THREAD

**Issue by kazoo-kmt** [alejandro-isaza/HDF5Kit#24]
readFixedLength() once worked for a hdf5 file to get the name of group, but when I tried to use it for a different hdf5 file, it threw an error. When I checked what was returned, it seemed the last element was not the value it should be returned.

```
(lldb) po layerNamesStringAttribute.read()
▿ 10 elements
  - 0 : "convolution1d_30"
  - 1 : "activation_46"
  - 2 : "reshape_12"
  - 3 : "convolution2d_41"
  - 4 : "activation_47"
  - 5 : "maxpooling2d_11"
  - 6 : "flatten_11"
  - 7 : "dense_21"
  - 8 : "activation_48"
  - 9 : "dense_2@�\u{16}p\u{01}"
```
The last element should be "dense_22".  I'll post if I find further information.

**Comment by alejandro-isaza** [comment]
this is fixed on https://github.com/alejandro-isaza/HDF5Kit/releases/tag/0.3.0
