### ISSUE TITLE
error: product dependency 'HDF5Kit' not found

### ISSUE THREAD

**Issue by rodrigoruiz** [alejandro-isaza/HDF5Kit#25]
I added `.package(url: "https://github.com/aleph7/CHDF5.git", from: "1.0.0")` to my dependencies and `"HDF5Kit"` to the target dependencies, but get that error.

**Comment by aleph7** [comment]
I updated master to Swift 4, give it a try now.

**Comment by rodrigoruiz** [comment]
Still nothing =/

**Comment by rodrigoruiz** [comment]
But actually there is nothing about Swift 4 in any release. Maybe you forgot to tag it?

**Comment by alejandro-isaza** [comment]
Sorry, this fell through the cracks. Uploaded 0.2.1 to Cocoapods and updated to Swift 4.2 on master.
