### ISSUE TITLE
Cocoapods + -Os Optimization may cause crash?

### ISSUE THREAD

**Issue by mhohmann** [alejandro-isaza/HDF5Kit#29]
I am trying to track down a crash that seems to happen sporadically for some people that use my application. 

The crash only occurs in release and not in debug, which lead me to think that it has something to do with the applied optimisation level to HDF5Kit upon release?

In the screenshot below, you see which function failed. Line 96 is a precondition statement, `precondition(data.count == size, "Data size doesn't match Dataspace dimensions")`

I already created a local copy of the data before giving it to the function to avoid changes to the dataset by other threats while storage is happening. That did not solve the issue.

Now, I set optimisation of the HD5Kit framework to -O0. This seems to have solved the issue.

Please let me know if I am missing something!
(I am using the latest release, 0.2.1

<img width="990" alt="screenshot_2018-11-26_at_12 43 21" src="https://user-images.githubusercontent.com/14195466/49027311-34efeb00-f1a0-11e8-9c1a-5d6711f2c755.png">

**Comment by mhohmann** [comment]
Update: This did not solve the issue, I have no idea what the problem could be.

**Comment by alejandro-isaza** [comment]
Make sure you are not accessing it from a separate thread. Also try running with the address sanitizer enabled.

**Comment by mhohmann** [comment]
Thank you for your quick reply. 
- All functions in question run on main. 
- The address sanitizer did not find anything either.

The issue only happens sporadically, and so far only in the release version of the app. I am unsure about how to debug this further?

**Comment by mhohmann** [comment]
Could this warning have something to do with the issue?
![screenshot 2018-11-26 at 20 01 10](https://user-images.githubusercontent.com/14195466/49035773-109f0900-f1b6-11e8-8f2a-54fb90227d39.png)

**Comment by alejandro-isaza** [comment]
What version are you using?

**Comment by mhohmann** [comment]
Xcode 10, Swift 4.2, and HDF5Kit 0.2.1, which is the latest release.

I am currently testing the removal of optimisation on the Pod project level for release, this seems to be stable

**Comment by alejandro-isaza** [comment]
try the latest master

**Comment by mhohmann** [comment]
I'll try that with everything else set back to default, thanks!

**Comment by mhohmann** [comment]
The master combined with the default pod configuration (-Os optimization) seems to be stable. 
Would you know why that is?

**Comment by alejandro-isaza** [comment]
@jonaswitt fixed a couple of issues. I can make a release.

**Comment by alejandro-isaza** [comment]
https://github.com/alejandro-isaza/HDF5Kit/releases/tag/0.3.0
