### ISSUE TITLE
Problem reading string attribute

### ISSUE THREAD

**Issue by LasCondes** [alejandro-isaza/HDF5Kit#32]
I'm using xcode 11.2 beta 2 and Swift 5.
I'm reading in a relatively small hdf5 file, 650kb.
I'm not able to read in string attributes or string dataset

        let a = group.openStringAttribute("category")
        let category = try a?.read()

            let list2 = listElementsGroup?.openStringDataset("materials_container_index_table")
            let a2 = try list2?.read()

Both of these throw an ioError

I can open the file in HDFView. In this capture I can read in the floating point "value" but not the category or the unit.

I'm not sure the best way to debug what is happening here.

<img width="816" alt="Screen Shot 2019-10-29 at 9 37 44 PM" src="https://user-images.githubusercontent.com/9662644/67821772-8aa9d300-fa94-11e9-95e8-b474e5acd8c3.png">

**Comment by alejandro-isaza** [comment]
Depending on how you are linking you may be able to set a breakpoint in `H5Aread` and see what specific error is being generated.

**Comment by LasCondes** [comment]
I copied some of the code into my project and I'm getting a return value of -1 H5Aread. The size agrees with the length of "Cartesian coordinates"

        if let a = group.openStringAttribute("category") {
            let variable = a.type.isVariableLengthString // false
            let id = a.id
            let space = a.space
            let count = a.space.size // 1
            let size = Int(H5Aget_storage_size(a.id)) // 21
            let stringSize = size / count
            
            var data = [CChar](repeating: 0, count: size)
            let type = Datatype.createString(size: stringSize + 1)
            try data.withUnsafeMutableBufferPointer { pointer in
                let status = H5Aread(id, type.id, pointer.baseAddress) // -1
                if status < 0 {
                    throw Error.ioError
                }
            }
            let category = try a.read()
        }

**Comment by LasCondes** [comment]
Here is the error detail I'm now reporting. How can I see what the src and dst datatypes are?

> HDF5-DIAG: Error detected in HDF5 (1.10.0) thread 0:
>   #000: /Users/andrew/GitHub/HDF5Kit/dist/src/H5A.c line 695 in H5Aread(): unable to read attribute
>     major: Attribute
>     minor: Read failed
>   #001: /Users/andrew/GitHub/HDF5Kit/dist/src/H5Aint.c line 524 in H5A__read(): unable to convert between src and dst datatypes
>     major: Attribute
>     minor: Feature is unsupported
>   #002: /Users/andrew/GitHub/HDF5Kit/dist/src/H5T.c line 4560 in H5T_path_find(): no appropriate function for conversion path
>     major: Datatype
>     minor: Unable to initialize object

**Comment by LasCondes** [comment]
From what I can tell the problem may be with reading the UTF8 character format.

https://support.hdfgroup.org/HDF5/doc/Advanced/UsingUnicode/index.html

my guess is 

    datatype_id = H5Tcopy(H5T_C_S1) ;
    error =       H5Tset_cset(datatype_id, H5T_CSET_UTF8) ;
    error =       H5Tset_size(datatype_id, "8") ;   

Needs to be added, for UTF strings, here:

https://github.com/alejandro-isaza/HDF5Kit/blob/d64976bd3dfaff29d5b4822be6c6f18c7c5621c2/Source/Datatype.swift#L80

**Comment by LasCondes** [comment]
I've made some progress.

In Datatype I've modified createString as follows

```
    public class func createString(size: Int = -1, utf8: Bool = false) -> Datatype {
        let id = H5Tcopy(H5T_C_S1_g)
        let type = Datatype(id: id)
        type.size = size
        if utf8 {
            H5Tset_cset(id, H5T_CSET_UTF8) // This was added
        }
        return type
    }
```

Then I've added this extension.

```
extension StringAttribute {
    
    public func readUTF8() throws -> [String] {
        if type.isVariableLengthString {
            return try readFixedLengthUTF8()
            // return try readVariableLength() // Don't have access to this here. Right now all the strings I'm reading are fixed length
        } else {
            return try readFixedLengthUTF8()
        }
    }
    
    func readFixedLengthUTF8() throws -> [String] {
        let count = self.space.size
        let size = Int(H5Aget_storage_size(id))
        let stringSize = size / count

        var data = [CChar](repeating: 0, count: size)
        let type = Datatype.createString(size: stringSize + 1, utf8: true) // This changed
        try data.withUnsafeMutableBufferPointer { pointer in
            let status = H5Aread(id, type.id, pointer.baseAddress)
            if status < 0 {
                throw Error.ioError
            }
        }

        var strings = [String]()
        strings.reserveCapacity(count)

        var index = 0
        for _ in 0 ..< count  { /// Keep getting  malloc: Heap corruption detected, free list is damaged at 0x600000cbeb20 here.
            data.withUnsafeBufferPointer { pointer in
                let string = String(cString: pointer.baseAddress! + index)
                strings.append(string)
                index += string.lengthOfBytes(using: .utf8) // This changed
                while index < size && pointer[index] == 0 {
                    index += 1
                }
            }
        }
        return strings
    }
}
```

It mostly works ... which is frustrating. I'm getting the occasional malloc: Heap corruption detected. As indicated in the comments. I do not know where this is being generated.

**Comment by alejandro-isaza** [comment]
Thanks for looking into this. I pushed a change that makes UTF8 the default for strings. Let me know if that fixes your problem.

**Comment by LasCondes** [comment]
In string attribute I'm getting a fatal error.

```
    func readFixedLength() throws -> [String] {
        let count = self.space.size
        let size = Int(H5Aget_storage_size(id))
        let stringSize = size / count

        var data = [CChar](repeating: 0, count: size)
        let type = Datatype.createString(size: stringSize + 1)
        try data.withUnsafeMutableBufferPointer { pointer in
            let status = H5Aread(id, type.id, pointer.baseAddress)
            if status < 0 {
                throw Error.ioError
            }
        }

        var strings = [String]()
        strings.reserveCapacity(count)

        var index = 0
        for _ in 0..<count {
            data.withUnsafeBufferPointer { pointer in
                let string = String(utf8String: pointer.baseAddress! + index)!
                strings.append(string)
                index += string.lengthOfBytes(using: .utf8)
                while index <= size && pointer[index] == 0 { // I'm getting a fatal error here. pointer length is 8 and index is 8
                    index += 1
                }
            }
        }
        return strings
    }
```

**Comment by alejandro-isaza** [comment]
I think it should be `while index < size && pointer[index] == 0`, `<` instead of `<=`.

**Comment by LasCondes** [comment]
Also when I use openStringDataset().read() the names are getting truncated [missing ending characters]

let list = try listElementsGroup.openStringDataset("geometry_container_index_table")?.read()

**Comment by alejandro-isaza** [comment]
Ok, I finally reproduced the problem in a test. Try the latest commit.

**Comment by LasCondes** [comment]
This is working great. Thank you.
